export enum OAuth2Scopes {
    bot = "bot",
    connection = "connection",
    email = "email",
    identify = "identify",
    guilds = "guilds",
    guildsJoin = "guilds.join",
    gdmJoin = "gdm.join",
    messagesRead = "messages.read",
    rpc = "rpc",
    rpcApi = "rpc.api",
    rpcNotificationsRead = "rpc.notifications.read",
    webhookIncoming = "webhook.incoming",
    applicationsBuildsUpload = "applications.builds.upload",
    applicationsBuildsRead = "applications.builds.read",
    applicationsStoreUpdate = "applications.store.update",
    applicationsEntitlements = "applications.entitlements",
    relationshipsRead = "relationships.read",
    activitiesRead = "activities.read",
    activitiesWrite = "activities.write",
}
